spring.application.name=faturamento
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=icompras-faturamento
spring.kafka.consumer.auto-offset-reset=earliest
icompras.config.kafka.topics.pedidos-pagos=icompras.pedidos-pagos
server.port =8083
minio.url=http://localhost:9000
minio.acess-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=icompras.faturas
